spring:
  datasource:
    generate-unique-name: false
    name: jdbc:h2:mem:tacocloudx
#    config:
#      import: file:env.properties
##    initialization-mode: always
##     FOR FIX DATA...
#    url: jdbc:h2:mem:tacocloud;INIT=RUNSCRIPT FROM 'src/main/resources/schema.sql'\;RUNSCRIPT FROM 'src/main/resources/data.sql';
#  jpa:
#    database-platform=org: hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true

# FOR MONGDO DB
#spring:
#  data:
#    mongodb:
#      host: mongodb.tacocloud.com
#      port: 27017
#      username: tacocloud
#      password: s3cr3tp455w0rd
#      database: tacoclouddb

#
#spring:
#  datasource:
#    generate-unique-name: false
#    url: jdbc:h2:mem:tacocloud
#    username:
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto:none
#  sql:
#    init:
#      mode:never

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope: email, public_profile