spring:
  datasource:
    generate-unique-name: false
    name: jdbc:h2:mem:tacocloud
#    initialization-mode: always
    url: jdbc:h2:mem:tacocloud;INIT=RUNSCRIPT FROM 'src/main/resources/schema.sql';
  jpa:
    generate-dll: false
    hibernate: ddl-auto
    defer-datasource-initialization: true
