---- This is config database from spring in action due to the using of "identity" in modern version H2

create table if not exists Taco_Order (
  id bigint generated by default as identity primary key,
  delivery_Name varchar(50) not null,
  delivery_Street varchar(50) not null,
  delivery_City varchar(50) not null,
  delivery_State varchar(2) not null,
  delivery_Zip varchar(10) not null,
  cc_number varchar(16) not null,
  cc_expiration varchar(5) not null,
  cc_cvv varchar(3) not null,
  placed_at timestamp not null
);

create table if not exists Taco (
  id bigint generated by default as identity primary key,
  name varchar(50) not null,
  taco_order bigint not null,
  taco_order_key bigint not null,
  created_at timestamp not null
);

create table if not exists Ingredient_Ref (
  ingredient varchar(4) not null,
  taco bigint not null,
  taco_key bigint not null
);

create table if not exists Ingredient (
  id varchar(4) primary key,
  name varchar(25) not null,
  type varchar(10) not null
);

alter table Taco add foreign key (taco_order) references Taco_Order(id);
alter table Ingredient_Ref add foreign key (ingredient) references Ingredient(id);

--CREATE SCHEMA IF NOT EXISTS tacocloud;
--USE tacocloud;
--
--CREATE TABLE IF NOT EXISTS Taco_Order (
--  id BIGINT PRIMARY KEY AUTO_INCREMENT,
--  delivery_Name VARCHAR(50) NOT NULL,
--  delivery_Street VARCHAR(50) NOT NULL,
--  delivery_City VARCHAR(50) NOT NULL,
--  delivery_State VARCHAR(2) NOT NULL,
--  delivery_Zip VARCHAR(10) NOT NULL,
--  cc_number VARCHAR(16) NOT NULL,
--  cc_expiration VARCHAR(5) NOT NULL,
--  cc_cvv VARCHAR(3) NOT NULL,
--  placed_at TIMESTAMP NOT NULL
--);
--
--CREATE TABLE IF NOT EXISTS Taco (
--  id BIGINT PRIMARY KEY AUTO_INCREMENT,
--  name VARCHAR(50) NOT NULL,
--  taco_order BIGINT NOT NULL,
--  taco_order_key BIGINT NOT NULL,
--  created_at TIMESTAMP NOT NULL
--);
--
--CREATE TABLE IF NOT EXISTS Ingredient_Ref (
--  id INT PRIMARY KEY AUTO_INCREMENT,
--  ingredient VARCHAR(4) NOT NULL,
--  taco BIGINT NOT NULL,
--  taco_key BIGINT NOT NULL,
--  FOREIGN KEY (ingredient) REFERENCES Ingredient(id)
--);
--
--CREATE TABLE IF NOT EXISTS Ingredient (
--  id INT PRIMARY KEY AUTO_INCREMENT,
--  name VARCHAR(25) NOT NULL,
--  type VARCHAR(10) NOT NULL
--);
--
--ALTER TABLE Taco ADD FOREIGN KEY (taco_order) REFERENCES Taco_Order(id);
